// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OsuStat.Data.Context;

#nullable disable

namespace OsuStat.Data.Migrations
{
    [DbContext(typeof(OsuStatDbContext))]
    [Migration("20260424103929_ChangeComboInEntity")]
    partial class ChangeComboInEntity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.7");

            modelBuilder.Entity("OsuStat.Data.Models.BeatmapEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Ar")
                        .HasColumnType("REAL");

                    b.Property<string>("Artist")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("BgPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Bpm")
                        .HasColumnType("REAL");

                    b.Property<double>("Cs")
                        .HasColumnType("REAL");

                    b.Property<double>("Hp")
                        .HasColumnType("REAL");

                    b.Property<string>("Length")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Mapper")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("StarRate")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("Beatmaps");
                });

            modelBuilder.Entity("OsuStat.Data.Models.PlayEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Accuracy")
                        .HasColumnType("REAL");

                    b.Property<long>("BeatmapId")
                        .HasColumnType("INTEGER");

                    b.Property<ushort>("Combo")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Grade")
                        .HasColumnType("INTEGER");

                    b.PrimitiveCollection<string>("Mods")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PlayedAt")
                        .HasColumnType("TEXT");

                    b.Property<double>("PpGained")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("BeatmapId");

                    b.ToTable("Plays");
                });

            modelBuilder.Entity("OsuStat.Data.Models.PlayerStatEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("AvgAccuracy")
                        .HasColumnType("REAL");

                    b.Property<double>("AvgBpm")
                        .HasColumnType("REAL");

                    b.Property<double>("AvgStarRate")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<int>("MapPlayed")
                        .HasColumnType("INTEGER");

                    b.Property<double>("PlayTimeMin")
                        .HasColumnType("REAL");

                    b.Property<double>("PpGained")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("Date")
                        .IsUnique();

                    b.ToTable("PlayerStats");
                });

            modelBuilder.Entity("OsuStat.Data.Models.PlayEntity", b =>
                {
                    b.HasOne("OsuStat.Data.Models.BeatmapEntity", "Beatmap")
                        .WithMany("Plays")
                        .HasForeignKey("BeatmapId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Beatmap");
                });

            modelBuilder.Entity("OsuStat.Data.Models.BeatmapEntity", b =>
                {
                    b.Navigation("Plays");
                });
#pragma warning restore 612, 618
        }
    }
}
